# 链接样式，参考 http://jekyllrb.com/docs/permalinks
permalink: /:categories/:year-:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
paginate: 7

markdown: redcarpet             # markdown 语法解释引擎
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
# 参考 http://github.com/vmg/redcarpet/blob/master/README.markdown

# 核心设置
title : Cheukyin.blog
tagline: Site Tagline
keywords : linux, archlinux, internet, sql, jekyll, embbed, cheukyin, python, emacs
description: Just for Fun
author :
  name : Cheukyin
  email : cheukyinyip0077@gmail.com
  github : cheukyin
  gitcafe : 
  twitter :
  facebook :
  feedburner :
  weibo : u/2529066905

# 域名连接
production_url : http://cheukyin.github.io

# Jekyll Bootstrap
JB :
  version : 0.3.0

  BASE_PATH : false                 # 如果不懂参数，请不要更改
  ASSET_PATH : false                # 同上

  # page
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # 评论，provider 留空或 false 关闭评论
  comments :
    provider : disqus              # 采用那种评论，duoshuo 或 disqus ....
    disqus :
      short_name : cheukyin-github
    livefyre :
      site_id :
    intensedebate :
      account :
    facebook :
      appid :
      num_posts:
      width: 580
      colorscheme: light
    duoshuo :
      name : cheukyin-github
      rcomments :                   # 首页侧边栏最新评论
        num: 10                     # 最新评论显示条数
        avatar : 0                  # 最新评论是否显示头像
        time: 0
        title : 0
        admin : 0
        length : 12                 # 最新评论显示的长度
      rvisitors :                   # 首页侧边栏最新访客
        num : 12                    # 最新访客数目
        size : 45                   # 最新访客头像的尺寸

  # 网站统计
  analytics :
    provider : false                # 采用那种统计，baidu 或 google ...
    google :
        tracking_id : 'UA-123-12'
    getclicky :
        site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik
    baidu :
        siteid: 707c49682d45342c4abaa7f2fbdd23dd        # 百度统计 js 代码后的字符串

  # 一键分享
  sharing :
    provider : baidu

  # CDN 加速资源
  cdn :
    jquery :
      #js : //cdn.bootcss.com/jquery/2.1.1/jquery.min.js
      js : //libs.useso.com/js/jquery/2.1.1/jquery.min.js
    webfont : false                  # google-fonts 开关，false 为关，留空或 true 为打开
    google-fonts :
      #js : //cdn.bootcss.com/webfont/1.3.0/webfont.min.js
      js : //libs.useso.com/js/webfont/1.3.0/webfont.min.js
    font-awesome :
      css : //cdn.bootcss.com/font-awesome/4.1.0/css/font-awesome.min.css
      #css : //libs.useso.com/js/font-awesome/4.1.0/css/font-awesome.min.css
    bootstrap :
      #js : //cdn.bootcss.com/twitter-bootstrap/3.1.1/js/bootstrap.min.js
      css : //cdn.bootcss.com/twitter-bootstrap/3.1.1/css/bootstrap.min.css
      js : //libs.useso.com/js/bootstrap/3.1.1/js/bootstrap.min.js
      #css : //libs.useso.com/js/bootstrap/3.1.1/css/bootstrap.min.css
    fancybox :
      #js : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
      #css : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
      js : //libs.useso.com/js/fancybox/2.1.5/jquery.fancybox.min.js
      css : //libs.useso.com/js/fancybox/2.1.5/jquery.fancybox.min.css

  # 友情链接
  blogroll : true                   # true 开启，留空或 false 关闭
  brlist :
    - text : 天镶·Blog
      url : //lingyu.wang/
    - text : Matrix67·Blog
      url : //www.matrix67.com/blog
    - text : CoolShell·Blog
      url : //coolshell.cn/
